//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wStoreData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTimeOffset EventDate { get; set; }
        public int NumberOfAttendees { get; set; }
        public string AddresLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public int Rating { get; set; }
    }
}
