//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wStoreData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFileStructure
    {
        public int FileID { get; set; }
        public string FileName { get; set; }
        public int ParentID { get; set; }
    }
}
